import org.jetbrains.kotlin.gradle.plugin.statistics.ReportStatisticsToElasticSearch.url

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java
    idea
    scala
    // Apply the application plugin to add support for building a CLI application.
    application
    kotlin("jvm") version "1.6.10"
    id("io.freefair.lombok") version "4.1.6"
    //    id ('cn.xinzhili.napp.autobuild')
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven("https://jcenter.bintray.com/")
    mavenCentral()
}

lombok {
    version.set("1.18.12")
    config.put("lombok.log.fieldName", "LOG")
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.10")

    implementation("org.scala-lang:scala-library:2.13.6")
    implementation("org.scala-lang:scala3-library_3:3.1.0-RC2")

    implementation(            "io.projectreactor:reactor-core:3.4.13")
    // Use JUnit test framework
    testImplementation("junit:junit:4.13")
}

application {
    // Define the main class for the application.
    mainClassName = "me.daqiang.base.App"
}


sourceSets {
    main {
        java {
            setSrcDirs(listOf("src/main/java", "src/main/kotlin", "src/main/scala"))
        }
    }
    test {
        java {
            setSrcDirs(listOf("src/test/java", "src/test/kotlin", "src/test/scala"))
        }
    }
}